server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery_service
    username: user
    password: delivery_user0913

  jpa:
    hibernate:
      ddl-auto: validate #Entity와의 매핑 판단만 테이블 변경x
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  sql:
    init:
      mode: never

  data:
    redis:
      host: localhost
      port: 6379