spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery_service
    username: user
    password: delivery_user0913

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate #Entity와의 매핑 판단만 테이블 변경x
    properties:
      hibernate:
        format_sql: true #sql 포맷하여 출력

  data:
    redis:
      host: localhost
      port: 6379

