name: CI With Gradle
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY_YML }}

    #    services:
    #      mysql:
    #        image: mysql:9.1.0
    #        env:
    #          MYSQL_ROOT_PASSWORD: delivery_root0913
    #          MYSQL_DATABASE: delivery_service
    #          MYSQL_USER: user
    #          MYSQL_PASSWORD: delivery_user0913
    #          TZ: Asia/Seoul
    #        ports:
    #          - "3306:3306"
    #      redis:
    #        image: redis:7.4
    #        ports:
    #          - "6379:6379"

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Create api-key.yml
        run: echo "$API_KEY" > api/src/main/resources/api-key.yml

      - name: Verify api-key.yml
        run: cat api/src/main/resources/api-key.yml

      - name: Docker Compose Up
        run: docker compose up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set file permissions for Gradle and Docker
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build