name: CI With Gradle
run-name: ${{ github.actor }} is testing out GitHub Actions

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY_YML }}

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Create api-key.yml
        run: echo "$API_KEY" > api/src/main/resources/api-key.yml

      - name: Docker Compose Up
        run: docker compose up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set file permissions for Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

#      - name: Test with Gradle Wrapper
#        run: ./gradlew test